dist: trusty
sudo: false
language: php

php:
  - 7.3
  - 7.4

env:
  - DB=mariadb
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update

install:
  - rm composer.lock
  - travis_retry composer update --no-interaction --prefer-dist --no-suggest --no-progress

script:
  - |
    if [[ "$DB" == "mysql" || "$DB" == "mariadb" ]]; then
      mysql -e "CREATE SCHEMA doctrine_tests; GRANT ALL PRIVILEGES ON doctrine_tests.* to travis@'%'";
    fi
  - ENABLE_SECOND_LEVEL_CACHE=0 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml
  # temporarily disabled
  #- ENABLE_SECOND_LEVEL_CACHE=1 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml --exclude-group performance,non-cacheable,locking_functional

jobs:
  include:
    - stage: Test
      env: DB=mariadb
      addons:
        mariadb: "10.4"

    - stage: Test
      env: DB=sqlite DEPENDENCIES=low
      install:
        - travis_retry composer update --no-interaction --prefer-dist --no-suggest --no-progress --prefer-lowest

    - stage: Test
      if: type = cron
      php: 7.3
      env: DB=sqlite DEV_DEPENDENCIES
      install:
        - rm composer.lock
        - composer config minimum-stability dev
        - travis_retry composer update --no-interaction --prefer-dist --no-suggest --no-progress

    - stage: Test
      env: DB=sqlite COVERAGE
      before_script:
        - phpenv config-add ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ENABLE_SECOND_LEVEL_CACHE=0 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml --coverage-clover ./build/logs/clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

    - stage: Code Quality
      env: DB=none BENCHMARK
      before_script:
        - wget https://phpbench.github.io/phpbench/phpbench.phar https://phpbench.github.io/phpbench/phpbench.phar.pubkey
      script:
        - php phpbench.phar run --bootstrap=tests/Doctrine/Tests/TestInit.php -l dots --report=default

  allow_failures:
    # temporarily disabled
    - env: DB=mysql
    - env: DB=mariadb
    - env: DB=pgsql

cache:
  directories:
    - $HOME/.composer/cache