dist: trusty
sudo: false
language: php

stages:
    - Smoke Testing
    - Test
    - Code Quality

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - DB=sqlite
  - DB=mysql
  - DB=pgsql

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install: travis_retry composer validate --strict && composer update --prefer-dist

script:
  - if [[ "$DB" == "mysql" || "$DB" == "mariadb" ]]; then mysql -e "CREATE SCHEMA doctrine_tests; GRANT ALL PRIVILEGES ON doctrine_tests.* to travis@'%'"; fi
  - ENABLE_SECOND_LEVEL_CACHE=0 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml
  - ENABLE_SECOND_LEVEL_CACHE=1 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml --exclude-group performance,non-cacheable,locking_functional

jobs:
  include:
    - stage: Smoke Testing
      env: DB=sqlite

    - stage: Test
      env: DB=mariadb
      addons:
        mariadb: 10.1

    - stage: Test
      dist: xenial
      env: DB=mysql MYSQL_VERSION=5.7
      php: 7.2
      services:
        - mysql
      before_script:
        - ./tests/travis/install-mysql-$MYSQL_VERSION.sh
      sudo: required

    - stage: Test
      dist: xenial
      env: DB=mysql MYSQL_VERSION=5.7
      php: 7.4
      services:
        - mysql
      before_script:
        - ./tests/travis/install-mysql-$MYSQL_VERSION.sh
      sudo: required

    - stage: Test
      env: DB=sqlite DEPENDENCIES=low
      install: travis_retry composer update --prefer-dist --prefer-lowest

    - stage: Test
      if: type = cron
      php: 7.3
      env: DB=sqlite DEV_DEPENDENCIES
      install:
        - composer config minimum-stability dev
        - travis_retry composer update --prefer-dist

    - stage: Test
      env: DB=sqlite COVERAGE
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ENABLE_SECOND_LEVEL_CACHE=0 ./vendor/bin/phpunit -v -c tests/travis/$DB.travis.xml --coverage-clover ./build/logs/clover.xml
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f ./build/logs/clover.xml

    - stage: Code Quality
      env: DB=none BENCHMARK
      php: 7.4
      before_script: wget https://github.com/phpbench/phpbench/releases/download/0.17.1/phpbench.phar https://phpbench.github.io/phpbench/phpbench.phar.pubkey
      script: php phpbench.phar run -l dots --report=default

    - stage: Code Quality
      if: NOT type = pull_request
      env: DB=none CODING_STANDARDS
      php: 7.4
      install: travis_retry composer install --prefer-dist
      script:
        - ./vendor/bin/phpcs

  allow_failures:
    - stage: Code Quality
      env: DB=none CODING_STANDARDS

cache:
  directories:
    - $HOME/.composer/cache
